### ISSUE TITLE
Other teams

### ISSUE THREAD

**Issue by unixjeff** [hazeluff/discord-nhlbot#19]
I would love to use this for the LA Kings if you plan to add/port to other teams

**Comment by hazeluff** [comment]
I do have plans, to have the bot for any NHL team.

At the moment, if you want to fork it, you should be able to change it quite easily to work for any other team.

**Comment by hazeluff** [comment]
FYI, I've started work on the generic NHLBot that works for all teams. (See https://github.com/hazeluff/discord-nhlbot/projects/3)

**Comment by unixjeff** [comment]
Awesome thank you!

**Comment by hazeluff** [comment]
Ok, i've implemented and hosted the changes needed...Try adding the bot using with this [link](https://discordapp.com/oauth2/authorize?client_id=257345858515894272&scope=bot&permissions=93200). And then running `@NHLBot#7894 subscribe lak`
