### ISSUE TITLE
Double Posting

### ISSUE THREAD

**Issue by unixjeff** [hazeluff/discord-nhlbot#32]
The bot is double posting

https://i.imgur.com/uzEsNkt.png

**Comment by hazeluff** [comment]
I think theres multiple processes running on the server. Ill have a look later. Cheers.

**Comment by hazeluff** [comment]
Wasn't multiple processes. I'll have to debug it. For now I'll roll back the server's version to 0.2.5

**Comment by hazeluff** [comment]
Problem existed because of latest changes. Channels were added multiple times to list of channels to message.

**Comment by hazeluff** [comment]
Deployed the latest 0.2.6 build to the server.
