### ISSUE TITLE
Bot Shows Offline

### ISSUE THREAD

**Issue by dinosaw** [hazeluff/discord-nhlbot#48]
I added the bot to my guild/server, but it just states that it's offline. I can't find anything else in the documentation telling me what I need to do. Is the bot down right now, or do I need to do something after adding it to my server?

**Comment by ZeykShade** [comment]
Likewise. Kicked bot, can't reinvite.

**Comment by hazeluff** [comment]
Sorry for the slow reply.

The bot's service stopped running on Thursday (coincides with your posts' dates), and had to be restarted. If you use the same link, he should be online. Sorry if he missed one of your games or something.

- Eugene
